/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Instructor = {
  _id: string;
  _type: 'instructor';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
};

export type SupportingCourse = {
  _id: string;
  _type: 'supportingCourse';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  courseTitle?: string;
  slug?: Slug;
  heroImage?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  order?: number;
  courseSeriesImage?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  courseDescription?: string;
  courseRequirements?: string;
  courseCarousel?: Array<
    {
      _key: string;
    } & CoursePhoto
  >;
  courseFooterImage?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  courseFooterText?: string;
};

export type CoursePhoto = {
  _type: 'coursePhoto';
  image?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  title?: string;
};

export type Course = {
  _id: string;
  _type: 'course';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  slug?: Slug;
  heroImage?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  courseNumber?: string;
  courseTitle?: string;
  order?: number;
  courseSeriesImage?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  courseDescription?: string;
  courseRequirements?: string;
  courseCarousel?: Array<
    {
      _key: string;
    } & CoursePhoto
  >;
  courseFooterImage?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  courseFooterText?: string;
};

export type Slug = {
  _type: 'slug';
  current?: string;
  source?: string;
};

export type MilitaryCoursesPage = {
  _id: string;
  _type: 'militaryCoursesPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroImage?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  title?: string;
  subtitle?: string;
  footerImage?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
};

export type MilitaryAboutPage = {
  _id: string;
  _type: 'militaryAboutPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  image1?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  image1_title?: string;
  image1_subTitle?: string;
  image2?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  image2_title?: string;
  image2_subTitle1?: string;
  image2_subTitle2?: string;
  image3?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  image3_title?: string;
  image3_subTitle?: string;
};

export type MilitaryLandingPage = {
  _id: string;
  _type: 'militaryLandingPage';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  image1?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  image1_title?: string;
  image2?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  image2_title?: string;
  image2_subTitle?: string;
  image3?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
};

export type SiteSettings = {
  _id: string;
  _type: 'siteSettings';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  favicon?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  militaryLogo?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  techLogo?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
  footerLogo?: {
    asset?: {
      _ref: string;
      _type: 'reference';
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type AllSanitySchemaTypes =
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityFileAsset
  | Geopoint
  | Instructor
  | SupportingCourse
  | CoursePhoto
  | Course
  | Slug
  | MilitaryCoursesPage
  | MilitaryAboutPage
  | MilitaryLandingPage
  | SiteSettings
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImageAsset
  | SanityAssetSourceData
  | SanityImageMetadata;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./sanity/sanity-utils.ts
// Variable: landingPageQuery
// Query: *[_type == "militaryLandingPage"][0]{  _id,  _createdAt,  "image1": image1.asset->url,  image1_title,  "image2": image2.asset->url,  image2_title,  image2_subTitle,  "image3": image3.asset->url,}
export type LandingPageQueryResult = {
  _id: string;
  _createdAt: string;
  image1: string | null;
  image1_title: string | null;
  image2: string | null;
  image2_title: string | null;
  image2_subTitle: string | null;
  image3: string | null;
} | null;
// Variable: aboutPageQuery
// Query: *[_type == "militaryAboutPage"][0]{  _id,  _createdAt,  "image1": image1.asset->url,  image1_title,  image1_subTitle,  "image2": image2.asset->url,  image2_title,  image2_subTitle1,  image2_subTitle2,  "image3": image3.asset->url,  image3_title,  image3_subTitle,}
export type AboutPageQueryResult = {
  _id: string;
  _createdAt: string;
  image1: string | null;
  image1_title: string | null;
  image1_subTitle: string | null;
  image2: string | null;
  image2_title: string | null;
  image2_subTitle1: string | null;
  image2_subTitle2: string | null;
  image3: string | null;
  image3_title: string | null;
  image3_subTitle: string | null;
} | null;
// Variable: militaryCoursesPageQuery
// Query: *[_type == "militaryCoursesPage"][0]{  _id,  _createdAt,  "heroImage": heroImage.asset->url,  title,  subtitle,  "footerImage": footerImage.asset->url,}
export type MilitaryCoursesPageQueryResult = {
  _id: string;
  _createdAt: string;
  heroImage: string | null;
  title: string | null;
  subtitle: string | null;
  footerImage: string | null;
} | null;
// Variable: getCoursesQuery
// Query: *[_type == "course"] | order(order asc){  _id,  courseNumber,  courseTitle,}
export type GetCoursesQueryResult = Array<{
  _id: string;
  courseNumber: string | null;
  courseTitle: string | null;
}>;
// Variable: getSupporingCoursesQuery
// Query: *[_type == "supportingCourses"] | order(order asc){  _id,  courseNumber,  courseTitle,}
export type GetSupporingCoursesQueryResult = Array<never>;
// Variable: getCourseQuery
// Query: *[_type == "course" && slug.current == $slug][0]{  _id,  "heroImage": heroImage.asset->url,  courseNumber,  courseTitle,  slug,  "courseSeriesImage": courseSeriesImage.asset->url,  courseDescription,  courseRequirements,  "courseFooterImage": courseFooterImage.asset->url,  courseFooterText,}
export type GetCourseQueryResult = {
  _id: string;
  heroImage: string | null;
  courseNumber: string | null;
  courseTitle: string | null;
  slug: Slug | null;
  courseSeriesImage: string | null;
  courseDescription: string | null;
  courseRequirements: string | null;
  courseFooterImage: string | null;
  courseFooterText: string | null;
} | null;
// Variable: getSupportingCourseQuery
// Query: *[_type == "supportingCourses" && slug.current == $slug][0]{  _id,  "heroImage": heroImage.asset->url,  courseNumber,  courseTitle,  slug,  courseDescription,  courseRequirements,  "courseSeriesImage": courseSeriesImage.asset->url,  "courseFooterImage": courseFooterImage.asset->url,  courseFooterText,}
export type GetSupportingCourseQueryResult = null;
